[features]
seeds = false
skip-lint = false

[programs.devnet]
nft_market = "CF2FBoCnN6bHgSUT1stncf9TwpgG5nAgntBRJp4eXChD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/wonder/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"	